In [3]:
#Numpy creating arrays--list
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
#using taple
import numpy as np
arr=np.array((1,2,3,4))
print(arr)
print(type(arr))


[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
#0-D array
import numpy as np
arr=np.array(42)
print(arr)

42


In [7]:
#1-D array
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [8]:
#2-D array
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
#3-D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
#prg to check how many dimension the array have
import numpy as np
a=np.array(23)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
#create an array with 5D and verify that it has 5D
import numpy as np
arr=np.array([1,2,3],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3]]]]]
number of dimensions: 5


In [12]:
#Accessing indexing 1-D
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
#adding element
print(arr[1]+arr[3])

1
2
3
4
6


In [14]:
#accsing 2-d array elements
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("5th elemnet from 2nd row:",arr[1][4])


5th elemnet from 2nd row: 10


In [16]:
#accsing 3-d array elements
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr[0][1][2])
#negative indexing
print(arr[1][0][-1])


6
3


In [18]:
#slicing array
import numpy as np
arr=np.array([1,2,3,4,5,6])
#slicing elements from 1 to index 5
print(arr[1:5])
#slicing elements from index 4 to end
print(arr[4:])
#from start to 4
print(arr[:4])
#from index 3 from end to 1 from end
print(arr[-3:-1])
#steps
print(arr[1:5:2])
#return ebvery elments from array
print(arr[::2])



[2 3 4 5]
[5 6]
[1 2 3 4]
[4 5]
[2 4]
[1 3 5]


In [20]:
#2d slicing
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[6 7 8]
[3 7]
[[2 3 4]
 [6 7 8]]
